import { createContext, ReactNode, useContext, useEffect, useState } from 'react';

export type AppLanguage = 'EN' | 'मर' | 'हि';

// Map our short codes to BCP-47 for the document `lang` attribute (audit DA-024).
const htmlLangCode: Record<AppLanguage, string> = { EN: 'en', 'मर': 'mr', 'हि': 'hi' };

interface LanguageContextType {
  lang: AppLanguage;
  setLang: (lang: AppLanguage) => void;
  t: (key: string, fallback: string) => string;
}

const dictionary: Record<AppLanguage, Record<string, string>> = {
  EN: {},
  'मर': {
    'app.search': 'कर्ज आणि सदस्य शोधा',
    'app.notifications': 'सूचना',
    'app.profile': 'माझी प्रोफाइल',
    'app.logout': 'लॉगआउट',
    'app.viewAll': 'सर्व सूचना पहा',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.myDashboard': 'माझा डॅशबोर्ड',
    'nav.applyLoan': 'कर्ज अर्ज',
    'nav.myLoans': 'माझी कर्जे',
    'nav.activeLoans': 'सक्रिय कर्जे',
    'nav.loanHistory': 'कर्ज इतिहास',
    'nav.myDocuments': 'माझी कागदपत्रे',
    'nav.repayment': 'पेमेंट करा',
    'nav.support': 'मदत व तक्रार',
    'nav.applicationInbox': 'अर्ज इनबॉक्स',
    'nav.newApplications': 'नवीन अर्ज',
    'nav.pendingAppraisal': 'मूल्यांकन प्रलंबित',
    'nav.returned': 'अपूर्ण अर्ज',
    'nav.memberRegistry': 'सदस्य नोंदणी',
    'nav.searchMember': 'सदस्य शोध',
    'nav.memberProfile': 'सदस्य प्रोफाइल',
    'nav.loanRegister': 'कर्ज नोंदणी',
    'nav.loanCalculator': 'कर्ज गणक',
    'nav.analytics': 'पोर्टफोलिओ विश्लेषण',
    'nav.dpd': 'DPD अहवाल',
    'nav.defaults': 'थकबाकी व वसुली',
    'nav.documentQueue': 'दस्तऐवज रांग',
    'nav.templates': 'दस्तऐवज नमुने',
    'nav.kyc': 'KYC व CKYC',
    'nav.calendar': 'अनुपालन दिनदर्शिका',
    'nav.noc': 'NOC व्यवस्थापन',
    'nav.stamp': 'स्टॅम्प ड्यूटी नोंदणी',
    'nav.reports': 'अहवाल',
    'nav.approvalQueue': 'मंजुरी रांग',
    'nav.sanctionRegister': 'मंजुरी नोंदणी',
    'nav.exceptions': 'अपवाद नोंदणी',
    'nav.board': 'बोर्ड मिनिट्स',
    'nav.policy': 'धोरण सेटिंग्ज',
    'nav.disbursement': 'वितरण रांग',
    'nav.sap': 'SAP व्यवस्थापन',
    'nav.incoming': 'प्राप्त पेमेंट',
    'nav.userManagement': 'वापरकर्ता व्यवस्थापन',
    'nav.audit': 'ऑडिट लॉग',
    'nav.config': 'सिस्टम सेटिंग्ज',
    // Login
    'login.welcome': 'पुन्हा स्वागत आहे',
    'login.subtitle': 'तुमच्या कर्ज पोर्टलमध्ये लॉग इन करा',
    'login.selectRole': 'तुमची भूमिका निवडा',
    // Farmer dashboard
    'fd.applyForLoan': 'कर्जासाठी अर्ज करा',
    'fd.previewState': 'पूर्वावलोकन स्थिती',
    'fd.goodStanding': 'तुमचे कर्ज सक्रिय व सुस्थितीत आहे',
    'fd.overdueTitle': 'हप्ता थकीत — दंड व्याज टाळण्यासाठी भरा',
    'fd.payNow': 'आता भरा',
    'fd.payOverdue': 'थकीत रक्कम भरा',
    'fd.payInstalment': 'हप्ता भरा',
    'fd.activeLoan': 'सक्रिय कर्ज',
    'fd.outstanding': 'थकबाकी शिल्लक',
    'fd.repaid': 'परतफेड',
    'fd.complete': 'पूर्ण',
    'fd.whatYouCanDo': 'तुम्ही आता काय करू शकता',
    'fd.borrowerCommand': 'कर्जदार नियंत्रण',
    'fd.trackLoan': 'कर्ज ट्रॅक करा',
    'fd.downloadFiles': 'कागदपत्रे डाउनलोड करा',
    'fd.applyAgain': 'पुन्हा अर्ज करा',
    'fd.askForHelp': 'मदत मागा',
    'fd.loanJourney': 'कर्ज प्रवास',
    'fd.recentTransactions': 'अलीकडील व्यवहार',
    'fd.documents': 'कागदपत्रे',
    'fd.recentAlerts': 'अलीकडील सूचना',
    'fd.viewAll': 'सर्व पहा',
    'fd.viewDetails': 'तपशील पहा',
    'fd.noLoanTitle': 'तुमच्याकडे सध्या सक्रिय कर्ज नाही',
    'fd.startFirst': 'तुमचा पहिला अर्ज सुरू करा',
    // Key Facts disclosure
    'kf.title': 'महत्त्वाची माहिती पत्रक',
    'kf.subtitle': 'तुमच्या कर्जाचे दर, शुल्क व अटी — सोप्या भाषेत',
    'kf.interestRate': 'व्याज दर',
    'kf.penalInterest': 'दंड व्याज',
    'kf.otherCharges': 'इतर शुल्क',
    'kf.tenure': 'मुदत',
    'kf.repaymentDate': 'परतफेड तारीख',
    'kf.security': 'तारण',
    'kf.dispute': 'तक्रार निवारण',
  },
  'हि': {
    'app.search': 'ऋण और सदस्य खोजें',
    'app.notifications': 'सूचनाएं',
    'app.profile': 'मेरी प्रोफाइल',
    'app.logout': 'लॉगआउट',
    'app.viewAll': 'सभी सूचनाएं देखें',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.myDashboard': 'मेरा डैशबोर्ड',
    'nav.applyLoan': 'ऋण आवेदन',
    'nav.myLoans': 'मेरे ऋण',
    'nav.activeLoans': 'सक्रिय ऋण',
    'nav.loanHistory': 'ऋण इतिहास',
    'nav.myDocuments': 'मेरे दस्तावेज',
    'nav.repayment': 'भुगतान करें',
    'nav.support': 'सहायता और शिकायत',
    'nav.applicationInbox': 'आवेदन इनबॉक्स',
    'nav.newApplications': 'नए आवेदन',
    'nav.pendingAppraisal': 'मूल्यांकन लंबित',
    'nav.returned': 'अधूरे आवेदन',
    'nav.memberRegistry': 'सदस्य रजिस्ट्री',
    'nav.searchMember': 'सदस्य खोज',
    'nav.memberProfile': 'सदस्य प्रोफाइल',
    'nav.loanRegister': 'ऋण रजिस्टर',
    'nav.loanCalculator': 'ऋण कैलकुलेटर',
    'nav.analytics': 'पोर्टफोलियो विश्लेषण',
    'nav.dpd': 'DPD रिपोर्ट',
    'nav.defaults': 'डिफॉल्ट और रिकवरी',
    'nav.documentQueue': 'दस्तावेज कतार',
    'nav.templates': 'दस्तावेज टेम्पलेट',
    'nav.kyc': 'KYC और CKYC',
    'nav.calendar': 'अनुपालन कैलेंडर',
    'nav.noc': 'NOC प्रबंधन',
    'nav.stamp': 'स्टाम्प ड्यूटी रजिस्टर',
    'nav.reports': 'रिपोर्ट',
    'nav.approvalQueue': 'स्वीकृति कतार',
    'nav.sanctionRegister': 'स्वीकृति रजिस्टर',
    'nav.exceptions': 'अपवाद रजिस्टर',
    'nav.board': 'बोर्ड मिनट्स',
    'nav.policy': 'नीति सेटिंग्स',
    'nav.disbursement': 'वितरण कतार',
    'nav.sap': 'SAP प्रबंधन',
    'nav.incoming': 'प्राप्त भुगतान',
    'nav.userManagement': 'उपयोगकर्ता प्रबंधन',
    'nav.audit': 'ऑडिट लॉग',
    'nav.config': 'सिस्टम सेटिंग्स',
    // Login
    'login.welcome': 'वापस स्वागत है',
    'login.subtitle': 'अपने ऋण पोर्टल में लॉग इन करें',
    'login.selectRole': 'अपनी भूमिका चुनें',
    // Farmer dashboard
    'fd.applyForLoan': 'ऋण के लिए आवेदन करें',
    'fd.previewState': 'पूर्वावलोकन स्थिति',
    'fd.goodStanding': 'आपका ऋण सक्रिय और सुस्थिति में है',
    'fd.overdueTitle': 'किस्त बकाया — दंड ब्याज से बचने हेतु भुगतान करें',
    'fd.payNow': 'अभी भुगतान करें',
    'fd.payOverdue': 'बकाया राशि भरें',
    'fd.payInstalment': 'किस्त भरें',
    'fd.activeLoan': 'सक्रिय ऋण',
    'fd.outstanding': 'बकाया शेष',
    'fd.repaid': 'चुकाया',
    'fd.complete': 'पूर्ण',
    'fd.whatYouCanDo': 'आप अभी क्या कर सकते हैं',
    'fd.borrowerCommand': 'उधारकर्ता नियंत्रण',
    'fd.trackLoan': 'ऋण ट्रैक करें',
    'fd.downloadFiles': 'दस्तावेज़ डाउनलोड करें',
    'fd.applyAgain': 'फिर से आवेदन करें',
    'fd.askForHelp': 'मदद मांगें',
    'fd.loanJourney': 'ऋण यात्रा',
    'fd.recentTransactions': 'हाल के लेन-देन',
    'fd.documents': 'दस्तावेज़',
    'fd.recentAlerts': 'हाल की सूचनाएं',
    'fd.viewAll': 'सभी देखें',
    'fd.viewDetails': 'विवरण देखें',
    'fd.noLoanTitle': 'आपके पास अभी कोई सक्रिय ऋण नहीं है',
    'fd.startFirst': 'अपना पहला आवेदन शुरू करें',
    // Key Facts disclosure
    'kf.title': 'मुख्य तथ्य विवरण',
    'kf.subtitle': 'आपके ऋण की दरें, शुल्क और शर्तें — सरल भाषा में',
    'kf.interestRate': 'ब्याज दर',
    'kf.penalInterest': 'दंड ब्याज',
    'kf.otherCharges': 'अन्य शुल्क',
    'kf.tenure': 'अवधि',
    'kf.repaymentDate': 'चुकौती तिथि',
    'kf.security': 'प्रतिभूति',
    'kf.dispute': 'विवाद समाधान',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'EN',
  setLang: () => {},
  t: (_, fallback) => fallback,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<AppLanguage>('EN');
  // Keep <html lang> in sync so screen readers announce the right language (audit DA-024).
  useEffect(() => { document.documentElement.lang = htmlLangCode[lang]; }, [lang]);
  const t = (key: string, fallback: string) => dictionary[lang][key] || fallback;
  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
